// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"jackpot-ts/app/model/internal"
)

// JackpotGlobalInfo is the golang structure for table jackpot_global_info.
type JackpotGlobalInfo internal.JackpotGlobalInfo

// Fill with you ideas below.
