// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"jackpot-ts/app/model/internal"
)

// JackpotPlayerInfo is the golang structure for table jackpot_player_info.
type JackpotPlayerInfo internal.JackpotPlayerInfo

// Fill with you ideas below.
