// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"jackpot-ts/app/model/internal"
)

// JackpotSpinRecord is the golang structure for table jackpot_spin_record.
type JackpotSpinRecord internal.JackpotSpinRecord

// Fill with you ideas below.
