// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"jackpot-ts/app/model/internal"
)

// MockMoney is the golang structure for table mock_money.
type MockMoney internal.MockMoney

// Fill with you ideas below.
