// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: entity_jackpot_spin_record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityJackpotSpinRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary",json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" orm:"id,primary"` //
	//@inject_tag: orm:"uid",json:"uid"
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid" orm:"uid"` //
	//@inject_tag: orm:"appid",json:"appid"
	Appid int32 `protobuf:"varint,3,opt,name=appid,proto3" json:"appid" orm:"appid"` //
	//@inject_tag: orm:"result_order",json:"result_order"
	ResultOrder int32 `protobuf:"varint,4,opt,name=result_order,json=resultOrder,proto3" json:"result_order" orm:"result_order"` //
	//@inject_tag: orm:"spin_time",json:"spin_time"
	SpinTime int64 `protobuf:"varint,5,opt,name=spin_time,json=spinTime,proto3" json:"spin_time" orm:"spin_time"` //
	//@inject_tag: orm:"stop_status",json:"stop_status"
	StopStatus string `protobuf:"bytes,6,opt,name=stop_status,json=stopStatus,proto3" json:"stop_status" orm:"stop_status"` //
	//@inject_tag: orm:"win_total_money",json:"win_total_money"
	WinTotalMoney int64 `protobuf:"varint,7,opt,name=win_total_money,json=winTotalMoney,proto3" json:"win_total_money" orm:"win_total_money"` //
	//@inject_tag: orm:"win_bonus_money",json:"win_bonus_money"
	WinBonusMoney int64 `protobuf:"varint,8,opt,name=win_bonus_money,json=winBonusMoney,proto3" json:"win_bonus_money" orm:"win_bonus_money"` //
	//@inject_tag: orm:"win_free_cnt",json:"win_free_cnt"
	WinFreeCnt int32 `protobuf:"varint,9,opt,name=win_free_cnt,json=winFreeCnt,proto3" json:"win_free_cnt" orm:"win_free_cnt"` //
	//@inject_tag: orm:"win_jackpot_money",json:"win_jackpot_money"
	WinJackpotMoney int64 `protobuf:"varint,10,opt,name=win_jackpot_money,json=winJackpotMoney,proto3" json:"win_jackpot_money" orm:"win_jackpot_money"` //
	//@inject_tag: orm:"win_bonus_item_cnt",json:"win_bonus_item_cnt"
	WinBonusItemCnt int32 `protobuf:"varint,11,opt,name=win_bonus_item_cnt,json=winBonusItemCnt,proto3" json:"win_bonus_item_cnt" orm:"win_bonus_item_cnt"` //
	//@inject_tag: orm:"win_related_items",json:"win_related_items"
	WinRelatedItems string `protobuf:"bytes,12,opt,name=win_related_items,json=winRelatedItems,proto3" json:"win_related_items" orm:"win_related_items"` //
}

func (x *EntityJackpotSpinRecord) Reset() {
	*x = EntityJackpotSpinRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_jackpot_spin_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityJackpotSpinRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityJackpotSpinRecord) ProtoMessage() {}

func (x *EntityJackpotSpinRecord) ProtoReflect() protoreflect.Message {
	mi := &file_entity_jackpot_spin_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityJackpotSpinRecord.ProtoReflect.Descriptor instead.
func (*EntityJackpotSpinRecord) Descriptor() ([]byte, []int) {
	return file_entity_jackpot_spin_record_proto_rawDescGZIP(), []int{0}
}

func (x *EntityJackpotSpinRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetAppid() int32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetResultOrder() int32 {
	if x != nil {
		return x.ResultOrder
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetSpinTime() int64 {
	if x != nil {
		return x.SpinTime
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetStopStatus() string {
	if x != nil {
		return x.StopStatus
	}
	return ""
}

func (x *EntityJackpotSpinRecord) GetWinTotalMoney() int64 {
	if x != nil {
		return x.WinTotalMoney
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetWinBonusMoney() int64 {
	if x != nil {
		return x.WinBonusMoney
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetWinFreeCnt() int32 {
	if x != nil {
		return x.WinFreeCnt
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetWinJackpotMoney() int64 {
	if x != nil {
		return x.WinJackpotMoney
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetWinBonusItemCnt() int32 {
	if x != nil {
		return x.WinBonusItemCnt
	}
	return 0
}

func (x *EntityJackpotSpinRecord) GetWinRelatedItems() string {
	if x != nil {
		return x.WinRelatedItems
	}
	return ""
}

var File_entity_jackpot_spin_record_proto protoreflect.FileDescriptor

var file_entity_jackpot_spin_record_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74,
	0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa9, 0x03, 0x0a, 0x17, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x70, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x6f, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x77,
	0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x77, 0x69, 0x6e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x77, 0x69, 0x6e, 0x5f, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x77, 0x69,
	0x6e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x77,
	0x69, 0x6e, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x77, 0x69, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6e, 0x74, 0x12, 0x2a, 0x0a,
	0x11, 0x77, 0x69, 0x6e, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x5f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x77, 0x69, 0x6e, 0x4a, 0x61, 0x63,
	0x6b, 0x70, 0x6f, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x12, 0x77, 0x69, 0x6e,
	0x5f, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x6e, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x77, 0x69, 0x6e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x43, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x77, 0x69, 0x6e, 0x5f, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x77, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_jackpot_spin_record_proto_rawDescOnce sync.Once
	file_entity_jackpot_spin_record_proto_rawDescData = file_entity_jackpot_spin_record_proto_rawDesc
)

func file_entity_jackpot_spin_record_proto_rawDescGZIP() []byte {
	file_entity_jackpot_spin_record_proto_rawDescOnce.Do(func() {
		file_entity_jackpot_spin_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_jackpot_spin_record_proto_rawDescData)
	})
	return file_entity_jackpot_spin_record_proto_rawDescData
}

var file_entity_jackpot_spin_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_jackpot_spin_record_proto_goTypes = []interface{}{
	(*EntityJackpotSpinRecord)(nil), // 0: pb.EntityJackpotSpinRecord
}
var file_entity_jackpot_spin_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_jackpot_spin_record_proto_init() }
func file_entity_jackpot_spin_record_proto_init() {
	if File_entity_jackpot_spin_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_jackpot_spin_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityJackpotSpinRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_jackpot_spin_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_jackpot_spin_record_proto_goTypes,
		DependencyIndexes: file_entity_jackpot_spin_record_proto_depIdxs,
		MessageInfos:      file_entity_jackpot_spin_record_proto_msgTypes,
	}.Build()
	File_entity_jackpot_spin_record_proto = out.File
	file_entity_jackpot_spin_record_proto_rawDesc = nil
	file_entity_jackpot_spin_record_proto_goTypes = nil
	file_entity_jackpot_spin_record_proto_depIdxs = nil
}
