// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: entity_mock_money.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityMockMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"uid,primary",json:"uid"
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid" orm:"uid,primary"` //
	//@inject_tag: orm:"money_type,primary",json:"money_type"
	MoneyType int32 `protobuf:"varint,2,opt,name=money_type,json=moneyType,proto3" json:"money_type" orm:"money_type,primary"` //
	//@inject_tag: orm:"money_cnt",json:"money_cnt"
	MoneyCnt int64 `protobuf:"varint,3,opt,name=money_cnt,json=moneyCnt,proto3" json:"money_cnt" orm:"money_cnt"` //
}

func (x *EntityMockMoney) Reset() {
	*x = EntityMockMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_mock_money_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityMockMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMockMoney) ProtoMessage() {}

func (x *EntityMockMoney) ProtoReflect() protoreflect.Message {
	mi := &file_entity_mock_money_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMockMoney.ProtoReflect.Descriptor instead.
func (*EntityMockMoney) Descriptor() ([]byte, []int) {
	return file_entity_mock_money_proto_rawDescGZIP(), []int{0}
}

func (x *EntityMockMoney) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityMockMoney) GetMoneyType() int32 {
	if x != nil {
		return x.MoneyType
	}
	return 0
}

func (x *EntityMockMoney) GetMoneyCnt() int64 {
	if x != nil {
		return x.MoneyCnt
	}
	return 0
}

var File_entity_mock_money_proto protoreflect.FileDescriptor

var file_entity_mock_money_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5f, 0x0a,
	0x0f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x63, 0x6b, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x43, 0x6e, 0x74, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_entity_mock_money_proto_rawDescOnce sync.Once
	file_entity_mock_money_proto_rawDescData = file_entity_mock_money_proto_rawDesc
)

func file_entity_mock_money_proto_rawDescGZIP() []byte {
	file_entity_mock_money_proto_rawDescOnce.Do(func() {
		file_entity_mock_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_mock_money_proto_rawDescData)
	})
	return file_entity_mock_money_proto_rawDescData
}

var file_entity_mock_money_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_mock_money_proto_goTypes = []interface{}{
	(*EntityMockMoney)(nil), // 0: pb.EntityMockMoney
}
var file_entity_mock_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_mock_money_proto_init() }
func file_entity_mock_money_proto_init() {
	if File_entity_mock_money_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_mock_money_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityMockMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_mock_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_mock_money_proto_goTypes,
		DependencyIndexes: file_entity_mock_money_proto_depIdxs,
		MessageInfos:      file_entity_mock_money_proto_msgTypes,
	}.Build()
	File_entity_mock_money_proto = out.File
	file_entity_mock_money_proto_rawDesc = nil
	file_entity_mock_money_proto_goTypes = nil
	file_entity_mock_money_proto_depIdxs = nil
}
