// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: entity_jackpot_player_info.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityJackpotPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"uid,primary",json:"uid"
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid" orm:"uid,primary"` //
	//@inject_tag: orm:"appid,primary",json:"appid"
	Appid int32 `protobuf:"varint,2,opt,name=appid,proto3" json:"appid" orm:"appid,primary"` //
	//@inject_tag: orm:"money",json:"money"
	Money int64 `protobuf:"varint,3,opt,name=money,proto3" json:"money" orm:"money"` //
	//@inject_tag: orm:"record_level",json:"record_level"
	RecordLevel int32 `protobuf:"varint,4,opt,name=record_level,json=recordLevel,proto3" json:"record_level" orm:"record_level"` //
	//@inject_tag: orm:"last_spin_time",json:"last_spin_time"
	LastSpinTime int64 `protobuf:"varint,5,opt,name=last_spin_time,json=lastSpinTime,proto3" json:"last_spin_time" orm:"last_spin_time"` //
	//@inject_tag: orm:"today_spin_cnt",json:"today_spin_cnt"
	TodaySpinCnt int32 `protobuf:"varint,6,opt,name=today_spin_cnt,json=todaySpinCnt,proto3" json:"today_spin_cnt" orm:"today_spin_cnt"` //
	//@inject_tag: orm:"bonus_progress",json:"bonus_progress"
	BonusProgress int32 `protobuf:"varint,7,opt,name=bonus_progress,json=bonusProgress,proto3" json:"bonus_progress" orm:"bonus_progress"` //
	//@inject_tag: orm:"bonus_cnt",json:"bonus_cnt"
	BonusCnt int64 `protobuf:"varint,8,opt,name=bonus_cnt,json=bonusCnt,proto3" json:"bonus_cnt" orm:"bonus_cnt"` //
	//@inject_tag: orm:"free_cnt",json:"free_cnt"
	FreeCnt int32 `protobuf:"varint,9,opt,name=free_cnt,json=freeCnt,proto3" json:"free_cnt" orm:"free_cnt"` //
	//@inject_tag: orm:"user_win_total",json:"user_win_total"
	UserWinTotal int64 `protobuf:"varint,10,opt,name=user_win_total,json=userWinTotal,proto3" json:"user_win_total" orm:"user_win_total"` //
}

func (x *EntityJackpotPlayerInfo) Reset() {
	*x = EntityJackpotPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_jackpot_player_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityJackpotPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityJackpotPlayerInfo) ProtoMessage() {}

func (x *EntityJackpotPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_jackpot_player_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityJackpotPlayerInfo.ProtoReflect.Descriptor instead.
func (*EntityJackpotPlayerInfo) Descriptor() ([]byte, []int) {
	return file_entity_jackpot_player_info_proto_rawDescGZIP(), []int{0}
}

func (x *EntityJackpotPlayerInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetAppid() int32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetRecordLevel() int32 {
	if x != nil {
		return x.RecordLevel
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetLastSpinTime() int64 {
	if x != nil {
		return x.LastSpinTime
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetTodaySpinCnt() int32 {
	if x != nil {
		return x.TodaySpinCnt
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetBonusProgress() int32 {
	if x != nil {
		return x.BonusProgress
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetBonusCnt() int64 {
	if x != nil {
		return x.BonusCnt
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetFreeCnt() int32 {
	if x != nil {
		return x.FreeCnt
	}
	return 0
}

func (x *EntityJackpotPlayerInfo) GetUserWinTotal() int64 {
	if x != nil {
		return x.UserWinTotal
	}
	return 0
}

var File_entity_jackpot_player_info_proto protoreflect.FileDescriptor

var file_entity_jackpot_player_info_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xcb, 0x02, 0x0a, 0x17, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x70, 0x69, 0x6e,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73,
	0x74, 0x53, 0x70, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x6f, 0x64,
	0x61, 0x79, 0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x53, 0x70, 0x69, 0x6e, 0x43, 0x6e, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f,
	0x63, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x43, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x63, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x43, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x77, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_jackpot_player_info_proto_rawDescOnce sync.Once
	file_entity_jackpot_player_info_proto_rawDescData = file_entity_jackpot_player_info_proto_rawDesc
)

func file_entity_jackpot_player_info_proto_rawDescGZIP() []byte {
	file_entity_jackpot_player_info_proto_rawDescOnce.Do(func() {
		file_entity_jackpot_player_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_jackpot_player_info_proto_rawDescData)
	})
	return file_entity_jackpot_player_info_proto_rawDescData
}

var file_entity_jackpot_player_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_jackpot_player_info_proto_goTypes = []interface{}{
	(*EntityJackpotPlayerInfo)(nil), // 0: pb.EntityJackpotPlayerInfo
}
var file_entity_jackpot_player_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_jackpot_player_info_proto_init() }
func file_entity_jackpot_player_info_proto_init() {
	if File_entity_jackpot_player_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_jackpot_player_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityJackpotPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_jackpot_player_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_jackpot_player_info_proto_goTypes,
		DependencyIndexes: file_entity_jackpot_player_info_proto_depIdxs,
		MessageInfos:      file_entity_jackpot_player_info_proto_msgTypes,
	}.Build()
	File_entity_jackpot_player_info_proto = out.File
	file_entity_jackpot_player_info_proto_rawDesc = nil
	file_entity_jackpot_player_info_proto_goTypes = nil
	file_entity_jackpot_player_info_proto_depIdxs = nil
}
