// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: entity_jackpot_global_info.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityJackpotGlobalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"pool_id,primary",json:"pool_id"
	PoolId int32 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id" orm:"pool_id,primary"` //
	//@inject_tag: orm:"money",json:"money"
	Money int64 `protobuf:"varint,2,opt,name=money,proto3" json:"money" orm:"money"` //
	//@inject_tag: orm:"user_win_total",json:"user_win_total"
	UserWinTotal int64 `protobuf:"varint,3,opt,name=user_win_total,json=userWinTotal,proto3" json:"user_win_total" orm:"user_win_total"` //
}

func (x *EntityJackpotGlobalInfo) Reset() {
	*x = EntityJackpotGlobalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_jackpot_global_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityJackpotGlobalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityJackpotGlobalInfo) ProtoMessage() {}

func (x *EntityJackpotGlobalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_jackpot_global_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityJackpotGlobalInfo.ProtoReflect.Descriptor instead.
func (*EntityJackpotGlobalInfo) Descriptor() ([]byte, []int) {
	return file_entity_jackpot_global_info_proto_rawDescGZIP(), []int{0}
}

func (x *EntityJackpotGlobalInfo) GetPoolId() int32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *EntityJackpotGlobalInfo) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *EntityJackpotGlobalInfo) GetUserWinTotal() int64 {
	if x != nil {
		return x.UserWinTotal
	}
	return 0
}

var File_entity_jackpot_global_info_proto protoreflect.FileDescriptor

var file_entity_jackpot_global_info_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74,
	0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6e, 0x0a, 0x17, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x24, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x77, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x57, 0x69,
	0x6e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_jackpot_global_info_proto_rawDescOnce sync.Once
	file_entity_jackpot_global_info_proto_rawDescData = file_entity_jackpot_global_info_proto_rawDesc
)

func file_entity_jackpot_global_info_proto_rawDescGZIP() []byte {
	file_entity_jackpot_global_info_proto_rawDescOnce.Do(func() {
		file_entity_jackpot_global_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_jackpot_global_info_proto_rawDescData)
	})
	return file_entity_jackpot_global_info_proto_rawDescData
}

var file_entity_jackpot_global_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_jackpot_global_info_proto_goTypes = []interface{}{
	(*EntityJackpotGlobalInfo)(nil), // 0: pb.EntityJackpotGlobalInfo
}
var file_entity_jackpot_global_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_jackpot_global_info_proto_init() }
func file_entity_jackpot_global_info_proto_init() {
	if File_entity_jackpot_global_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_jackpot_global_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityJackpotGlobalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_jackpot_global_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_jackpot_global_info_proto_goTypes,
		DependencyIndexes: file_entity_jackpot_global_info_proto_depIdxs,
		MessageInfos:      file_entity_jackpot_global_info_proto_msgTypes,
	}.Build()
	File_entity_jackpot_global_info_proto = out.File
	file_entity_jackpot_global_info_proto_rawDesc = nil
	file_entity_jackpot_global_info_proto_goTypes = nil
	file_entity_jackpot_global_info_proto_depIdxs = nil
}
