// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// JackpotPlayerInfo is the golang structure for table jackpot_player_info.
type JackpotPlayerInfo struct {
	UID           int64 `orm:"uid,primary"    json:"uid"`            //
	Appid         int32 `orm:"appid,primary"  json:"appid"`          //
	Money         int64 `orm:"money"          json:"money"`          //
	RecordLevel   int32 `orm:"record_level"   json:"record_level"`   //
	LastSpinTime  int64 `orm:"last_spin_time" json:"last_spin_time"` //
	TodaySpinCnt  int32 `orm:"today_spin_cnt" json:"today_spin_cnt"` //
	BonusProgress int32 `orm:"bonus_progress" json:"bonus_progress"` //
	BonusCnt      int64 `orm:"bonus_cnt"      json:"bonus_cnt"`      //
	FreeCnt       int32 `orm:"free_cnt"       json:"free_cnt"`       //
	UserWinTotal  int64 `orm:"user_win_total" json:"user_win_total"` //
}
