// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// JackpotGlobalInfo is the golang structure for table jackpot_global_info.
type JackpotGlobalInfo struct {
	PoolID       int32 `orm:"pool_id,primary" json:"pool_id"`        //
	Money        int64 `orm:"money"           json:"money"`          //
	UserWinTotal int64 `orm:"user_win_total"  json:"user_win_total"` //
}
