// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// JackpotSpinRecord is the golang structure for table jackpot_spin_record.
type JackpotSpinRecord struct {
	ID              int64  `orm:"id,primary"         json:"id"`                 //
	UID             int64  `orm:"uid"                json:"uid"`                //
	Appid           int32  `orm:"appid"              json:"appid"`              //
	ResultOrder     int32  `orm:"result_order"       json:"result_order"`       //
	SpinTime        int64  `orm:"spin_time"          json:"spin_time"`          //
	StopStatus      string `orm:"stop_status"        json:"stop_status"`        //
	WinTotalMoney   int64  `orm:"win_total_money"    json:"win_total_money"`    //
	WinBonusMoney   int64  `orm:"win_bonus_money"    json:"win_bonus_money"`    //
	WinFreeCnt      int32  `orm:"win_free_cnt"       json:"win_free_cnt"`       //
	WinJackpotMoney int64  `orm:"win_jackpot_money"  json:"win_jackpot_money"`  //
	WinBonusItemCnt int32  `orm:"win_bonus_item_cnt" json:"win_bonus_item_cnt"` //
	WinRelatedItems string `orm:"win_related_items"  json:"win_related_items"`  //
}
