// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"jackpot-ts/app/dao/internal"
)

// jackpotSpinRecordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type jackpotSpinRecordDao struct {
	internal.JackpotSpinRecordDao
}

var (
	// JackpotSpinRecord is globally public accessible object for table jackpot_spin_record operations.
	JackpotSpinRecord = jackpotSpinRecordDao{
		internal.JackpotSpinRecord,
	}
)

// Fill with you ideas below.
