// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"jackpot-ts/app/dao/internal"
)

// jackpotGlobalInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type jackpotGlobalInfoDao struct {
	internal.JackpotGlobalInfoDao
}

var (
	// JackpotGlobalInfo is globally public accessible object for table jackpot_global_info operations.
	JackpotGlobalInfo = jackpotGlobalInfoDao{
		internal.JackpotGlobalInfo,
	}
)

// Fill with you ideas below.
