// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"jackpot-ts/app/dao/internal"
)

// mockMoneyDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type mockMoneyDao struct {
	internal.MockMoneyDao
}

var (
	// MockMoney is globally public accessible object for table mock_money operations.
	MockMoney = mockMoneyDao{
		internal.MockMoney,
	}
)

// Fill with you ideas below.
